<a href="https://colab.research.google.com/github/danicaroa/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix and Its Operations

Create a NumPy program that performs the operations of the given matrices:

1 sum = A +B 

2 difference1 = B - A

3 difference2 = A - B

In [ ]:
import numpy as np
a = np.array([[-5,0],[4,1]]) 
b = np.array([[6,-3],[2,3]])
sum = a + b
print (sum)

[[ 1 -3]
 [ 6  4]]


In [ ]:
import numpy as np
a = np.array([[-5,0],[4,1]]) 
b = np.array([[6,-3],[2,3]])
difference1 = b - a
print (difference1)

[[11 -3]
 [-2  2]]


In [ ]:
import numpy as np
a = np.array([[-5,0],[4,1]]) 
b = np.array([[6,-3],[2,3]])
difference2 = a - b
print (difference2)

[[-11   3]
 [  2  -2]]
