<a href="https://colab.research.google.com/github/danicaroa/Numerical-Methods/blob/main/ROA_MATRIX_ALGEBRA_NUMERICAL_METHOD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## MATRIX AND ITS OPERATIONS

1 x 3 ARRAY

In [ ]:
import numpy as np
a = np.array([1,2,3]) #This is example of 1 x 3 array
print(a)

[1 2 3]


In [ ]:
import numpy as np
a = np.array([1,2,3]) #This is example of 1 x 3 array
a[0]=4
print(a)

[4 2 3]


2 x 3 matrix

In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #This is example of 2 x 3 matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #This is example of 2 x 3 matrix
print(b)
print(b.shape) #shape

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #This is example of 2 x 3 matrix
b[0,0]=7 #method
print(b)

[[7 2 3]
 [4 5 6]]


3 X 3 MATRIX

In [ ]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #This is example of Square matrix

print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
d = np.full((2,2),6)  
print(d)

[[6 6]
 [6 6]]


IDENTITY MATRIX

In [ ]:
import numpy as np
e = np.eye(2) #eye = identity
print(e)

[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
f = np.diagonal([[1,2,3],[4,5,6],[7,8,9]]) #This is example of Diagonal Identity

print(f)

[1 5 9]


EMPTY MATRIX

In [ ]:
import numpy as np
g = np.empty((0,10))

print(g)

[]


In [ ]:
import numpy as np
h = np.zeros((2,2))
print(h)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
i = np.eye(2) #eye = identity
j = np.zeros((2,2))
print(i)
print(j)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
i = np.eye(2) #eye = identity
j = np.zeros((2,2))
print(i+j)

[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
i = np.eye(2) #eye = identity
j = np.zeros((2,2))
print(i)
print(j)
print(i+j)  #gets the summation of the matrices i and j
print(i-j)  #gets the difference of the matrices i and j
print(j-i)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
